create table player (id serial primary key, firstname text, lastname text, email text, score integer, submit_date timestamp, duration integer);
create table reponse (id serial primary key, f_player_id serial, type text, index integer, question text, reponse integer, bonne_reponse integer, temps_reponse integer);

create table question (id serial primary key, type text, index integer, libelle text, reponse_1 text, reponse_2 text, reponse_3 text, reponse_4 text, bonne_reponse integer);

insert into question values (1, 'Web', 1, 'Dans la tribu web nous nous interessons au monde Web dans sa globalité. Nous testons, nous développons, nous découvrons et nous nous entraidons. L''ecosystème évolue tellement vite, que nous profitons du travail de chacun afin de rester toujours à la pointe de l''expertise.', '', '', '', '', 0);
insert into question values (2, 'Web', 2, 'Quelle librairie JavaScript développée par Facebook est devenu l''une des solutions les plus utilisées pour développer des application Web ?', 'jQuery', 'Prototype', 'Flow', 'React', 4);
insert into question values (3, 'Web', 3, 'Quel task runner très utilisé se base sur le système de Stream de NodeJS pour définir l''ordre d''exécution de votre workflow ?', 'Grunt', 'Maven', 'Gulp', 'Broccoli' , 3);

insert into question values (4, 'BigData', 1, 'Tout se résume par la donnée, qu''elle soit mobile, distribuée, structurée ou non ... Son stockage et puis son analyse, devient de plus en plus complexe.Afin de mieux accompagner nos clients, de devenir meilleurs, acquérir une certaine expérience, échanger, venez nous rejoindre si vous êtes intéressés et partager vos connaissances.', '', '', '', '', 0);
insert into question values (5, 'BigData', 2, 'En 2016 est apparue la Stack Big Data SMACK. Chaque lettre de l''acronyme SMACK correspond à une technologie Big data. Êtes vous capable de citer l''ensemble des technologies ?', 'Samza, Microservice, Avro, CouchDB, Kubernetes', 'Storm, Mahout, Ambari, CouchBase, Kudu', 'Spark, Mesos, Akka, Cassandra, Kafka', 'La réponse D', 3);
insert into question values (6, 'BigData', 3, 'Lequel de ces termes ne désigne pas un algorithmes de Machine Learning', 'Atomic regression', 'Random forest', 'K-Means', 'SVM', 1);

insert into question values (7, 'DevOps', 1, 'Les réunions de la tribu permettent de partager des retours d''expérience, veille techno ou des lectures. Elles ont aussi pour but de favoriser les envies de collaboration pour tous ceux qui ont envie d''aller plus loin et de monter en équipe des projets, des démos… Bon on va pas vous mentir, on en profite aussi pour juste se retrouver et boire un verre entre potes !', '', '', '', '', 0);
insert into question values (8, 'DevOps', 2, 'Que signifie l''acronyme “CAMS”', 'Collaboration As a Measurable System', 'Culture Automation Measurement Share', 'Container Automated Multiple Services', 'Call Asap My Sysadmin', 2);
insert into question values (9, 'DevOps', 3, 'Lequel de ces termes ne désigne pas un outil d''intégration continue ', 'TravisCI', 'CircleCI', 'ChanCI', 'Jenkins', 3);

insert into question values (10, 'Agile', 1, 'Etre agile, chez Zenika, c''est faire grandir les individus, les équipes et les organisations en suivant les valeurs et les principes agiles. C''est aider nos clients à cultiver leurs produits pour maximiser l''impact et la valeur qu''ils peuvent produire.', '', '', '', '', 0);
insert into question values (11, 'Agile', 2, 'Comment Scrum garantit la qualité du produit ?', 'En injectant des testeurs au sein de l''équipe de réalisation', 'En exigeant que tous les “test cases” soient rédigés avant le début du sprint', 'En ajoutant un sprint de stabilisation pour éxécuter tous les QA', 'En negociant une définition de “terminé” entre le PO et les équipes de réalisation', 4);
insert into question values (12, 'Agile', 3, 'Comment sont distribuées les responsabilités du chef de projet au sein d''une équipe Scrum ?', 'Il n''y pas de Chef de Projet dans une équipe Scrum', 'Les responsabilités sont distribuées entre le SM, l''équipe de réalisation et le PO', 'Le SM assume les reponsabilités du Chef de Projet', 'Le PO assume les responsabilités du Chef de Projet', 2);

insert into question values (13, 'Craftsmanship', 1, 'L''esprit software craftsmanship est avant tout une recherche de l''excellence dans le métier de développeur. Cette excellence est acquise par la pratique, le partage de connaissances et le développement de ses compétences. Nous nous inspirons de sociétés comme 8th light et de professionnels comme Uncle Bob et Sandro Mancuso. Concrètement, nous organisons des coding dojo, écrivons des articles, parlons de nos lectures...', '', '', '', '', 0);
insert into question values (14, 'Craftsmanship', 2, 'Question 1 Que signifie l''acronyme “KISS” ?', 'Keep It Simple Stupid', 'Keep Integers Super Small', 'Keep Imagine Simple Solutions', 'Kirikou Is Super Strong', 1);
insert into question values (15, 'Craftsmanship', 3, 'Quel langage ne peut pas se voir appliquer les principes du Craftsmanship ?', 'Java', 'C#', 'Javascript', 'Aucun' , 4);

insert into question values (16, 'IOT', 1, 'Si tes parents t''ont offert ton premier robot programmable pour tes 6 ans et que tu l''as démonté pour contrôler tes Mécanos motorisés, que tu t''es acheté un super téléphone pour faire plaisir à ... heu... toi même, si tu aimes développer sur des chouettes gadgets que tu es le seul à trouver utile ou si encore tu aimes découvrir de nouvelles bières à chaque réunion, alors la tribu IoT est faite pour toi !', '', '', '', '', 0);
insert into question values (17, 'IOT', 2, 'Quelle réponse n''est pas une technologie de communication de l''IoT ?', 'Lora', 'AMQP', 'BLE', 'Sigfox', 2);
insert into question values (18, 'IOT', 3, 'Que signifie CQRS ?', 'Command and Query Responsibility Segregation', 'Control of Quality Responsability Systems', 'Connnected and Qualified Responsive Systems', 'Comment Qualifier cette Réponse Simplement', 1);

insert into question values (19, 'Java', 1, 'L''informatique ne s''arrête pas à la maîtrise d''une technologie ou d''une méthodologie, la tribu Architecture propose une vision globale des enjeux logiciels qui peuvent intéresser les clients. Si tu veux rendre sexy le legacy de ton quotidien en maîtrisant les tenants et aboutissants, viens trouver et proposer chez nous les axes et méthodologies pour accompagner ton client dans sa mutation vers l''excellence logicielle.', '', '', '', '', 0);
insert into question values (20, 'Java', 2, 'Quelle phrase au sujet de Java est correcte ?', 'En Java, les types de base ne sont pas des objets', 'Java supporte l''héritage multiple entre les classes', 'En Java, on peut affecter soi-même l''adresse d''un pointeur', 'Java supporte la surcharge des opérateurs' , 1);
insert into question values (21, 'Java', 3, 'Comment indiquer qu''une classe A hérite d''une classe B ?', 'class A ::B', 'class A extends B', 'class A implements B', 'class A inherit B' , 2);